ns(): bump PowerDNS version, remove unused tools

diff --git a/ns/Dockerfile b/ns/Dockerfile
--- a/ns/Dockerfile
+++ b/ns/Dockerfile
@@ -1,6 +1,11 @@
-FROM debian:jessie
+FROM debian:stretch
 
-RUN echo 'deb http://repo.powerdns.com/debian jessie-auth-40 main' \
+RUN set -ex \
+	# Prepare for adding repository
+	&& apt-get update \
+	&& apt-get install -y curl gnupg
+
+RUN echo 'deb [arch=amd64] http://repo.powerdns.com/debian stretch-auth-41 main' \
       >> /etc/apt/sources.list \
  && echo 'Package: pdns-*' \
       > /etc/apt/preferences.d/pdns \
@@ -10,15 +15,14 @@ RUN echo 'deb http://repo.powerdns.com/debian jessie-auth-40 main' \
       >> /etc/apt/preferences.d/pdns
 
 RUN set -ex \
-	&& apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv 0x1B0C6205FD380FBB \
+	&& curl https://repo.powerdns.com/FD380FBB-pub.asc | apt-key add - \
 	&& apt-get update \
 	&& apt-get install -y pdns-server pdns-backend-mysql \
 	# credentials management via envsubst
 	&& apt-get -y install gettext-base \
 	# Post-create cron hook
-	&& apt-get -y install cron curl jq mariadb-client \
-	# debugging tools
-	&& apt-get -y install dnsutils net-tools \
+	&& apt-get -y install cron mariadb-client \
+	# cleanup
 	&& apt-get clean \
 	&& rm -rf /var/lib/apt/lists/*
 
